### ISSUE TITLE
Public Key Infrastructure/Raw Public Key Support

### ISSUE THREAD

**Issue by pulsastrix** [namib-project/libcoap-rs#4]
## Summary

Allow for usage of Raw Public Keys and/or a Public Key Infrastructure instead of pre-shared keys to establish DTLS sessions.

## Description

We currently do not expose the API required for using raw public keys or certificates instead of symmetric pre-shared keys for DTLS session establishment. 
This should obviously be changed.

## Implementation steps

- [ ] Design Rust-idiomatic API
- [ ] Implement wrapper code
- [ ] Add tests (ideally also for PSK, since PSK currently has no tests)

(Issue moved over from GitLab)
