### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by pulsastrix** [namib-project/libcoap-rs#5]
## Summary

libcoap-rs currently has rather limited error-handling capabilities. This should be improved.

## Description

While libcoap-rs has some error handling support, it falls short in some regards:
- No library-internal logging
  - The `log` crate would allow library users to use their own logging framework while still allowing us to provide log output
- Some errors are silently ignored
  - While message parsing errors are responded to with an RST message, the library user is not informed of such malformed requests. It might be useful if users could provide callbacks/event handlers for such events
- We might want to re-evaluate if there are some places where we `panic` even though we should return a `Result`
- libcoap is rather limited in its error output: Most functions simply return a value on success and `NULL` on failure, making it rather hard to pinpoint the exact reason for this error.
  - Fixing this would probably require some large changes in libcoap as we would have to implement error codes throughout the entire library

## Implementation steps
- [ ] Add some library-internal logging
  - [ ] Integrate the `log` crate and add logging messages where reasonable
  - [ ] Redirect libcoap's own logging to the log crate (see [`coap_set_log_handler()`](https://libcoap.net/doc/reference/develop/group__logging.html#ga0577c5a45b04d26f30a64e8e604b458e))
- [ ] Add event handler methods for error handling
- [ ] Evaluate all panics
- [ ] (Optional: Add error codes and error code retrieval functions to libcoap)
