### ISSUE TITLE
Migrate CI pipeline and issue templates to GitHub

### ISSUE THREAD

**Issue by pulsastrix** [namib-project/libcoap-rs#6]
## Summary/Description
Currently, we only have CI pipeline configurations for GitLab, this should be adjusted.
Additionally, we should probably also adapt the issue templates accordingly.

## Implementation steps
- [x] Adapt GitLab CI pipeline configuration to GitHub Actions
- [ ] Move and adapt issue templates over somewhere where GitHub can find them
- [ ] Test CI pipeline
